[package]
name = "damadama"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
cargo_toml = { workspace = true }
clap = { workspace = true }
derive_more = { workspace = true }
either = { workspace = true }
getset = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
smartstring = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
typed-builder = { workspace = true }
