[package]
name = "damadama"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
cargo_toml = { workspace = true }
clap = { workspace = true }
crossbeam = { workspace = true }
derive-new = { workspace = true }
derive_more = { workspace = true }
either = { workspace = true }
futures = { workspace = true }
getset = { workspace = true }
humantime = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
once_cell = { workspace = true }
owo-colors = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shrinkwraprs = { workspace = true }
smartstring = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-indicatif = { workspace = true }
tracing-subscriber = { workspace = true }
typed-builder = { workspace = true }
walkdir = { workspace = true }
