omit_targets = []
extra_srcs = []
src_referenced_dirs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = [":libc"]
filter_deps = []
cargo_env = false

[env]

[[buildscript]]
[buildscript.build]

[[buildscript]]
unresolved = 'Unresolved build script at vendor/derive_builder-0.7.2/build/mod.rs. Dependencies:'

[extra_mapped_srcs]

[platform_fixup]
