omit_targets = []
extra_srcs = []
src_referenced_dirs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = []
filter_deps = []
cargo_env = false

[env]

[[buildscript]]
[buildscript.build]

[[buildscript]]
unresolved = '''
Unresolved build script at vendor/rstest_macros-0.17.0/build.rs. Dependencies:
    rustc_version-0.4.0'''

[extra_mapped_srcs]

[platform_fixup]
