omit_targets = []
extra_srcs = []
src_referenced_dirs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = []
filter_deps = []
cargo_env = false

[env]

[[buildscript]]
[buildscript.build]

[[buildscript]]
unresolved = '''
Unresolved build script at vendor/palette-0.4.1/build/main.rs. Dependencies:
    phf_codegen-0.7.24'''

[extra_mapped_srcs]

[platform_fixup]
