omit_targets = []
extra_srcs = []
src_referenced_dirs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = []
filter_deps = []
cargo_env = false

[env]

[[buildscript]]
[buildscript.build]

[[buildscript]]
unresolved = '''
Unresolved build script at vendor/phonenumber-0.3.2+8.13.9/build.rs. Dependencies:
    bincode-1.3.3
    bincode-1.3.3
    quick-xml-0.28.1
    quick-xml-0.28.1
    regex-1.7.3
    regex-1.7.3
    serde-1.0.159
    serde-1.0.159
    serde_derive-1.0.159
    serde_derive-1.0.159
    thiserror-1.0.40
    thiserror-1.0.40'''

[extra_mapped_srcs]

[platform_fixup]
