omit_targets = []
extra_srcs = []
src_referenced_dirs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = []
filter_deps = []
cargo_env = false

[env]

[[buildscript]]
[buildscript.build]

[[buildscript]]
unresolved = '''
Unresolved build script at vendor/rand_chacha-0.1.1/build.rs. Dependencies:
    autocfg-0.1.8'''

[extra_mapped_srcs]

[platform_fixup]
