omit_targets = []
extra_srcs = []
src_referenced_dirs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = []
filter_deps = []
cargo_env = false

[env]

[[buildscript]]
[buildscript.build]

[[buildscript]]
unresolved = '''
Unresolved build script at vendor/mime_guess-2.0.4/build.rs. Dependencies:
    unicase-2.6.0
    unicase-2.6.0'''

[extra_mapped_srcs]

[platform_fixup]
