[package]
name = "pb_cache"
version = "0.1.0"
edition = "2021"
authors = ["pulanski"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# cached = { workspace = true }
derive-new = { workspace = true }
derive_more = { workspace = true }
futures = { workspace = true }
getset = { workspace = true }
indicatif = { workspace = true }
lazy_static = { workspace = true }
miette = { workspace = true }
once_cell = { workspace = true }
owo-colors = { workspace = true }
parking_lot = { workspace = true }
# progress = { workspace = true }
rand = { workspace = true }
shrinkwraprs = { workspace = true }
smartstring = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-indicatif = { workspace = true }
tracing-subscriber = { workspace = true }
typed-builder = { workspace = true }
ulid = { workspace = true }
